[package]
authors = ["Fredrik Andersson <krueger71@users.noreply.github.com>"]
description = "Intel 8080 Space Invaders Emulator"
edition = "2021"
license = "MIT"
name = "inv8080rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
